language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
rvm:
  - 2.7.3
  - 2.3.0
  - 2.2.0
  - 2.1.0
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - POSTGRES_TO_REDSHIFT_SOURCE_URI=postgres://postgres@localhost/travis_ci_test
